"""initial migration

Revision ID: 1cee7cfbfc64
Revises: 
Create Date: 2026-03-04 01:41:08.808374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cee7cfbfc64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sla_alert_minutes', sa.Integer(), nullable=True))
        batch_op.drop_column('sla_default_minutes')
        batch_op.drop_column('sla_warning_minutes')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sla_warning_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sla_default_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('sla_alert_minutes')
        batch_op.drop_column('plan')
        batch_op.drop_column('sla_minutes')

    # ### end Alembic commands ###
